[build]
  command = "pip install -r requirements.txt && python3 build_static.py"
  publish = "frontend"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
